name: Manual Release & Publish

on:
  workflow_dispatch: # only runs manually from Actions tab

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      - name: Build
        run: npm run build

      - name: Check for changes in lib/
        id: libchanges
        run: |
          git diff --quiet HEAD^ HEAD -- lib/ || echo "lib_changed=true" >> $GITHUB_ENV

      - name: Bump version & changelog
        if: env.lib_changed == 'true'
        run: npm run release
        env:
          HUSKY: 0

      - name: Push changes
        if: env.lib_changed == 'true'
        run: |
          git push origin master --follow-tags

      - name: Publish package
        if: env.lib_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
